# Generated by Django 4.0.4 on 2022-04-29 12:50

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/no_image.png', upload_to=profiles.models.upload_to),
        ),
    ]
