# Generated by Django 4.0.4 on 2022-05-11 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critic_score', models.FloatField(blank=True, help_text='Aggregate score compiled by Metacritic staff', null=True)),
                ('critic_count', models.FloatField(blank=True, help_text='The number of critics used in coming up with the Critic_score', null=True)),
                ('user_score', models.FloatField(blank=True, help_text='Score by Metacritic`s subscribers', null=True)),
                ('user_count', models.FloatField(blank=True, help_text='Number of users who gave the user_score', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('platform', models.CharField(blank=True, max_length=30, null=True)),
                ('publisher', models.CharField(blank=True, max_length=30, null=True)),
                ('developer', models.CharField(blank=True, max_length=30, null=True)),
                ('genre', models.CharField(blank=True, max_length=30, null=True)),
                ('year_of_release', models.IntegerField(blank=True, null=True)),
                ('esrb_rating', models.CharField(blank=True, choices=[('K-A', 'Kids to Adults, 6+'), ('M', 'Mature, 17+'), ('RP', 'Rating Pending'), ('E', 'Everyone'), ('AO', 'Adults Only, 18+'), ('E10+', 'Everyone 10+'), ('EC', 'Early Childhood, 3+'), ('T', 'Teen, 13+')], max_length=4, null=True)),
                ('rating', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.rating')),
            ],
        ),
    ]
