# Generated by Django 4.0.4 on 2022-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year_of_release',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
