# Generated by Django 4.0.4 on 2022-04-14 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_year_of_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb_rating',
            field=models.CharField(blank=True, choices=[('K-A', 'Kids to Adults, 6+'), ('M', 'Mature, 17+'), ('RP', 'Rating Pending'), ('E', 'Everyone'), ('AO', 'Adults Only, 18+'), ('E10+', 'Everyone 10+'), ('EC', 'Early Childhood, 3+'), ('T', 'Teen, 13+')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='critic_count',
            field=models.FloatField(blank=True, help_text='The number of critics used in coming up with the Critic_score', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='critic_score',
            field=models.FloatField(blank=True, help_text='Aggregate score compiled by Metacritic staff', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_count',
            field=models.FloatField(blank=True, help_text='Number of users who gave the user_score', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_score',
            field=models.FloatField(blank=True, help_text='Score by Metacritic`s subscribers', null=True),
        ),
    ]
