# Generated by Django 4.0.4 on 2022-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_uuid_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb_rating',
            field=models.CharField(blank=True, choices=[('K-A', 'Kids to Adults, 6+'), ('M', 'Mature, 17+'), ('RP', 'Rating Pending'), ('E', 'Everyone'), ('AO', 'Adults Only, 18+'), ('E10+', 'Everyone 10+'), ('EC', 'Early Childhood, 3+'), ('T', 'Teen, 13+')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
