# Generated by Django 4.0.4 on 2022-04-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_developer_alter_game_esrb_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.rating'),
        ),
    ]
