# Generated by Django 4.0.4 on 2022-04-15 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
