# Generated by Django 4.0.4 on 2022-04-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.rating'),
        ),
    ]
