# Generated by Django 4.0.4 on 2022-04-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb_rating',
            field=models.CharField(blank=True, choices=[('K-A', 'Kids to Adults, 6+'), ('M', 'Mature, 17+'), ('RP', 'Rating Pending'), ('E', 'Everyone'), ('AO', 'Adults Only, 18+'), ('E10+', 'Everyone 10+'), ('EC', 'Early Childhood, 3+'), ('T', 'Teen, 13+')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
