# Generated by Django 4.0.4 on 2022-04-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NA_sales', models.FloatField(blank=True, help_text='Game sales in North America (in millions of units)')),
                ('EU_sales', models.FloatField(blank=True, help_text='Game sales in the European Union (in millions of units)')),
                ('JP_sales', models.FloatField(blank=True, help_text='Game sales in Japan (in millions of units)')),
                ('other_sales', models.FloatField(blank=True, help_text='Game sales in the rest of the world, i.e. Africa, Asiaexcluding Japan, Australia, Europe excluding the E.U. and')),
                ('global_sales', models.FloatField(blank=True, help_text='Total sales in the world (in millions of units)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
