# Generated by Django 4.0.4 on 2022-04-15 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_product_sale_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
