# Generated by Django 4.0.4 on 2022-04-16 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
