# Generated by Django 4.0.4 on 2022-04-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_created_sale_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='EU_sales',
            field=models.FloatField(blank=True, help_text='Game sales in the European Union (in millions of units)', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='JP_sales',
            field=models.FloatField(blank=True, help_text='Game sales in Japan (in millions of units)', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='NA_sales',
            field=models.FloatField(blank=True, help_text='Game sales in North America (in millions of units)', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='global_sales',
            field=models.FloatField(blank=True, help_text='Total sales in the world (in millions of units)', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='other_sales',
            field=models.FloatField(blank=True, help_text='Game sales in the rest of the world, i.e. Africa, Asiaexcluding Japan, Australia, Europe excluding the E.U. and', null=True),
        ),
    ]
