# Generated by Django 4.0.4 on 2022-05-11 14:34

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('bio', models.TextField(default='no bio...')),
                ('avatar', models.ImageField(default='profiles/no_image.png', upload_to=test_app.models.upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
